### ISSUE TITLE
[BUG] venv podman-compose detection is broken

### ISSUE THREAD

**Issue by aarron-lee** [eylenburg/linoffice#94]
quickstart.sh complains that podman-compose is not installed in the venv, even though it actually is in the venv.

running setup.sh also says that podman-compose is not installed in the venv.

See Below:

```bash
# setup.sh
INFO: Checking if podman is installed
SUCCESS: podman is installed: podman version 5.7.0
INFO: Checking if podman-compose is installed
INFO: Python environment: Virtual environment at /home/aarron/.local/bin/linoffice/venv
ERROR: podman-compose is not installed in virtual environment.

        HOW TO FIX:
        The virtual environment needs podman-compose installed.
        Run: /home/aarron/.local/bin/linoffice/venv/bin/python3 -m pip install podman-compose
```

```
# checking venv for podman-compose
$ /home/aarron/.local/bin/linoffice/venv/bin/python3 -m pip install podman-compose

Requirement already satisfied: podman-compose in /home/aarron/.local/bin/linoffice/venv/lib/python3.14/site-packages (1.5.0)
Requirement already satisfied: python-dotenv in /home/aarron/.local/bin/linoffice/venv/lib/python3.14/site-packages (from podman-compose) (1.2.1)
Requirement already satisfied: pyyaml in /home/aarron/.local/lib/python3.14/site-packages (from podman-compose) (6.0.3)
```

**System information**
- LinOffice version: Latest
- Linux distribution: [Bazzite DX](https://dev.bazzite.gg/)
- Desktop environment: KDE
- Wayland
- How did you install Podman-Compose (e.g. from repo or via pip): VENV

**Comment by aarron-lee** [comment]
temporary workaround:

run quickstart.sh once to generate the venv

then run

```bash
source ~/.local/bin/linoffice/venv/bin/activate
~/.local/bin/linoffice/quickstart.sh
```

edit: this might not necessarily work, I had to modify the code to get it to work again.

**Comment by Wallace4444** [comment]
For me - I ran:
cp /usr/lib/python3.14/site-packages/podman_compose.py /.local/lib/python3.14/site-packages/podman_compose.py

That file not existing in that location was causing all the problems for me. I had the same symptoms as described above.

**Comment by eylenburg** [comment]
Should hopefully be fixed in v2.2.5

**Comment by tie-sko** [comment]
I still have this problem on Fedora 43:

```
...
SUCCESS: podman is installed: podman version 5.7.1
INFO: Checking if podman-compose is installed
INFO: Python environment: System Python
INFO: podman-compose at /usr/bin/podman-compose points to missing interpreter:
INFO: podman-compose at /usr/bin/podman-compose points to missing interpreter:
INFO: podman-compose at /usr/bin/podman-compose points to missing interpreter:
ERROR: podman-compose is present at /usr/bin/podman-compose but cannot run (likely a stale venv-generated wrapper).

HOW TO FIX:
1. Remove the broken wrapper: rm -f /usr/bin/podman-compose
2. Reinstall podman-compose (e.g. dnf install podman-compose, apt install podman-compose, or pip3 install --user podman-compose)
```

I followed the fix steps, which give the same result.

**Comment by eylenburg** [comment]
This is hopefully fixed by https://github.com/eylenburg/linoffice/commit/3cd37b3448af75c938f45eb7c0a5693b98224b7f in v 2.2.6
